from app.models.user import User
from app.models.customer import Customer
from app.models.service_plan import ServicePlan
from app.models.address import Address
from app.models.kyc import KycDocument
from app.models.sim_card import SimCard
from app.models.sim_replacement import SimReplacement
from app.models.device import Device
from app.models.device_assignment import DeviceAssignment
from app.models.subscription import Subscription
from app.models.subscription_history import SubscriptionHistory
from app.models.usage_record import UsageRecord
from app.models.tower import Tower
from app.models.tower_coverage import TowerCoverage
from app.models.equipment import Equipment
from app.models.equipment_metrics import EquipmentMetric
from app.models.outage import Outage
from app.models.outage_tower import OutageTower
from app.models.outage_customer import OutageCustomer
from app.models.technician import Technician
from app.models.technician_skill import TechnicianSkill
from app.models.support_ticket import SupportTicket
from app.models.technician_assignment import TechnicianAssignment
from app.models.ticket_assignment import TicketAssignment
from app.models.ticket_comment import TicketComment
from app.models.ticket_history import TicketHistory
from app.models.sla_rule import SlaRule
from app.models.sla_tracking import SlaTracking
from app.models.service_request import ServiceRequest
from app.models.service_request_history import ServiceRequestHistory
from app.models.notification import Notification
from app.models.audit_log import AuditLog
